import { ConfiguratorDataModel } from './models/data.model';

export const data: Array<ConfiguratorDataModel> = [
    {
        setType: 'STRXL18MOV0',
        type: '18MOV0',
        partNumber: '6008845P2',
        description: 'CoRoent® XL+, 8x18x45mm',
        material: 'PEEK',
        available: 5,
        H: 8,
        L: 26,
        W: 45,
        lordosis: 0,
        qtyInSet: 2
    },
    {
        setType: 'STRXL18MOV0',
        type: '18MOV0',
        partNumber: '6008845P2',
        description: 'CoRoent® XL+, 8x18x45mm',
        material: 'PEEK',
        available: 5,
        H: 8,
        L: 16,
        W: 45,
        lordosis: 10,
        qtyInSet: 2
    },
    {
        setType: 'STRXL18MOV0',
        type: '18MOV0',
        partNumber: '6008845P2',
        description: 'CoRoent® XL+, 8x18x45mm',
        material: 'PEEK',
        available: 5,
        H: 8,
        L: 16,
        W: 45,
        lordosis: 20,
        qtyInSet: 2
    },        
    {
        setType: 'STRXL18MOV0',
        type: '18MOV0',
        partNumber: '6008850P2',
        description: 'CoRoent® XL+, 8x18x50mm',
        material: 'PEEK2',
        available: 5,
        H: 8,
        L: 22,
        W: 50,
        lordosis: 10,
        qtyInSet: 2
    },   
    {
        setType: 'STRXL18M',
        type: '18MOV0',
        partNumber: '6008850P2',
        description: 'CoRoent® XL+, 8x18x50mm',
        material: 'PEEK_TEST',
        available: 5,
        H: 8,
        L: 18,
        W: 50,
        lordosis: 15,
        qtyInSet: 2
    },
    {
        setType: 'STRXL18M',
        type: '18MOV0',
        partNumber: '6008850P2',
        description: 'CoRoent® XL+, 8x18x50mm',
        material: 'PEEK',
        available: 5,
        H: 8,
        L: 38,
        W: 50,
        lordosis: 25,
        qtyInSet: 2
    },
    {
        setType: 'STRXL18M',
        type: '18MOV0',
        partNumber: '6008850P2',
        description: 'CoRoent® XL+, 8x18x50mm',
        material: 'PEEK',
        available: 5,
        H: 8,
        L: 28,
        W: 50,
        lordosis: 25,
        qtyInSet: 4
    },
    {
        setType: 'STRXL18M',
        type: '18MOV0',
        partNumber: '6008850P2',
        description: 'CoRoent® XL+, 8x18x50mm',
        material: 'PEEK',
        available: 5,
        H: 8,
        L: 28,
        W: 50,
        lordosis: 15,
        qtyInSet: 4
    },
    {
        setType: 'STRXL18M',
        type: '18MOV0',
        partNumber: '6008850P2',
        description: 'CoRoent® XL+, 8x18x50mm',
        material: 'PEEK',
        available: 5,
        H: 4,
        L: 8,
        W: 50,
        lordosis: 15,
        qtyInSet: 4
    },
    {
        setType: 'STRXL18M',
        type: '18MOV0',
        partNumber: '6008850P2',
        description: 'CoRoent® XL+, 8x18x50mm',
        material: 'PEEK',
        available: 5,
        H: 6,
        L: 4,
        W: 50,
        lordosis: 35,
        qtyInSet: 4
    },
    {
        setType: 'STRXL18M',
        type: '18MOV0',
        partNumber: '6008850P2',
        description: 'CoRoent® XL+, 8x18x50mm',
        material: 'PEEK',
        available: 5,
        H: 6,
        L: 4,
        W: 50,
        lordosis: 45,
        qtyInSet: 4
    },
    {
        setType: 'STRXL18M',
        type: '18MOV0',
        partNumber: '6008850P2',
        description: 'CoRoent® XL+, 8x18x50mm',
        material: 'PEEK',
        available: 5,
        H: 6,
        L: 4,
        W: 50,
        lordosis: 55,
        qtyInSet: 4
    },
    {
        setType: 'STRXL18M',
        type: '18MOV0',
        partNumber: '6008850P2',
        description: 'CoRoent® XL+, 8x18x50mm',
        material: 'PEEK2',
        available: 5,
        H: 8,
        L: 28,
        W: 50,
        lordosis: 25,
        qtyInSet: 4
    },
    {
        setType: 'STRXL18M',
        type: '18MOV0',
        partNumber: '6008850P2',
        description: 'CoRoent® XL+, 8x18x50mm',
        material: 'PEEK2',
        available: 5,
        H: 8,
        L: 28,
        W: 50,
        lordosis: 15,
        qtyInSet: 4
    },
    {
        setType: 'STRXL18M',
        type: '18MOV0',
        partNumber: '6008850P2',
        description: 'CoRoent® XL+, 8x18x50mm',
        material: 'PEEK2',
        available: 5,
        H: 4,
        L: 8,
        W: 50,
        lordosis: 15,
        qtyInSet: 4
    },
    {
        setType: 'STRXL18M',
        type: '18MOV0',
        partNumber: '6008850P2',
        description: 'CoRoent® XL+, 8x18x50mm',
        material: 'PEEK2',
        available: 5,
        H: 6,
        L: 4,
        W: 50,
        lordosis: 35,
        qtyInSet: 4
    },
    {
        setType: 'STRXL18M',
        type: '18MOV0',
        partNumber: '6008850P2',
        description: 'CoRoent® XL+, 8x18x50mm',
        material: 'PEEK2',
        available: 5,
        H: 6,
        L: 4,
        W: 50,
        lordosis: 45,
        qtyInSet: 4
    },
    {
        setType: 'STRXL18M',
        type: '18MOV0',
        partNumber: '6008850P2',
        description: 'CoRoent® XL+, 8x18x50mm',
        material: 'PEEK2',
        available: 5,
        H: 6,
        L: 4,
        W: 50,
        lordosis: 55,
        qtyInSet: 4
    }                                                        
]