import { IConfiguratorDataModel } from './models/models';
import { INIT_STATE } from '../RawData/data';


export const DEFAULT_MATERIAL = 'PEEK';
export const DATA: Array<IConfiguratorDataModel> = INIT_STATE.raw;

// export const DATA: Array<IConfiguratorDataModel> = [
//     {
//         setType: 'CORXL0MOV',
//         type: '18MOV0',
//         partNumber: '6908845',
//         description: 'CoRoent® XL, 8x18x45mm',
//         material: 'PEEK',
//         H: 8,
//         L: 18,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL0MOV',
//         type: '18MOV0',
//         partNumber: '6908850',
//         description: 'CoRoent® XL, 8x18x50mm',
//         material: 'PEEK',
//         H: 8,
//         L: 18,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL0MOV',
//         type: '18MOV0',
//         partNumber: '6908855',
//         description: 'CoRoent® XL, 8x18x55mm',
//         material: 'PEEK',
//         H: 8,
//         L: 18,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL0MOV',
//         type: '18MOV0',
//         partNumber: '6908860',
//         description: 'CoRoent® XL, 8x18x60mm',
//         material: 'PEEK',
//         H: 8,
//         L: 18,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL0MOV',
//         type: '18MOV0',
//         partNumber: '6910845',
//         description: 'CoRoent® XL, 10x18x45mm',
//         material: 'PEEK',
//         H: 10,
//         L: 18,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL0MOV',
//         type: '18MOV0',
//         partNumber: '6910850',
//         description: 'CoRoent® XL, 10x18x50mm',
//         material: 'PEEK',
//         H: 10,
//         L: 18,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL0MOV',
//         type: '18MOV0',
//         partNumber: '6910855',
//         description: 'CoRoent® XL, 10x18x55mm',
//         material: 'PEEK',
//         H: 10,
//         L: 18,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL0MOV',
//         type: '18MOV0',
//         partNumber: '6910860',
//         description: 'CoRoent® XL, 10x18x60mm',
//         material: 'PEEK',
//         H: 10,
//         L: 18,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL0MOV',
//         type: '18MOV0',
//         partNumber: '6912845',
//         description: 'CoRoent® XL, 12x18x45mm',
//         material: 'PEEK',
//         H: 12,
//         L: 18,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL0MOV',
//         type: '18MOV0',
//         partNumber: '6912850',
//         description: 'CoRoent® XL, 12x18x50mm',
//         material: 'PEEK',
//         H: 12,
//         L: 18,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL0MOV',
//         type: '18MOV0',
//         partNumber: '6912855',
//         description: 'CoRoent® XL, 12x18x55mm',
//         material: 'PEEK',
//         H: 12,
//         L: 18,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL0MOV',
//         type: '18MOV0',
//         partNumber: '6912860',
//         description: 'CoRoent® XL, 12x18x60mm',
//         material: 'PEEK',
//         H: 12,
//         L: 18,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL10MOV',
//         type: '18MOV10',
//         partNumber: '6980845',
//         description: 'CoRoent® XL, 8x18x45mm 10°',
//         material: 'PEEK',
//         H: 8,
//         L: 18,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL10MOV',
//         type: '18MOV10',
//         partNumber: '6980850',
//         description: 'CoRoent® XL, 8x18x50mm 10°',
//         material: 'PEEK',
//         H: 8,
//         L: 18,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL10MOV',
//         type: '18MOV10',
//         partNumber: '6980855',
//         description: 'CoRoent® XL, 8x18x55mm 10°',
//         material: 'PEEK',
//         H: 8,
//         L: 18,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL10MOV',
//         type: '18MOV10',
//         partNumber: '6980860',
//         description: 'CoRoent® XL, 8x18x60mm 10°',
//         material: 'PEEK',
//         H: 8,
//         L: 18,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL10MOV',
//         type: '18MOV10',
//         partNumber: '6981045',
//         description: 'CoRoent® XL, 10x18x45mm 10°',
//         material: 'PEEK',
//         H: 10,
//         L: 18,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL10MOV',
//         type: '18MOV10',
//         partNumber: '6981050',
//         description: 'CoRoent® XL, 10x18x50mm 10°',
//         material: 'PEEK',
//         H: 10,
//         L: 18,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL10MOV',
//         type: '18MOV10',
//         partNumber: '6981055',
//         description: 'CoRoent® XL, 10x18x55mm 10°',
//         material: 'PEEK',
//         H: 10,
//         L: 18,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL10MOV',
//         type: '18MOV10',
//         partNumber: '6981060',
//         description: 'CoRoent® XL, 10x18x60mm 10°',
//         material: 'PEEK',
//         H: 10,
//         L: 18,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL10MOV',
//         type: '18MOV10',
//         partNumber: '6981245',
//         description: 'CoRoent® XL, 12x18x45mm 10°',
//         material: 'PEEK',
//         H: 12,
//         L: 18,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL10MOV',
//         type: '18MOV10',
//         partNumber: '6981250',
//         description: 'CoRoent® XL, 12x18x50mm 10°',
//         material: 'PEEK',
//         H: 12,
//         L: 18,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL10MOV',
//         type: '18MOV10',
//         partNumber: '6981255',
//         description: 'CoRoent® XL, 12x18x55mm 10°',
//         material: 'PEEK',
//         H: 12,
//         L: 18,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXL10MOV',
//         type: '18MOV10',
//         partNumber: '6981260',
//         description: 'CoRoent® XL, 12x18x60mm 10°',
//         material: 'PEEK',
//         H: 12,
//         L: 18,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLOUT',
//         type: '18OUT',
//         partNumber: '6908840',
//         description: 'CoRoent® XL, 8x18x40mm',
//         material: 'PEEK',
//         H: 8,
//         L: 18,
//         W: 40,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLOUT',
//         type: '18OUT',
//         partNumber: '6910840',
//         description: 'CoRoent® XL, 10x18x40mm',
//         material: 'PEEK',
//         H: 10,
//         L: 18,
//         W: 40,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLOUT',
//         type: '18OUT',
//         partNumber: '6912840',
//         description: 'CoRoent® XL, 12x18x40mm',
//         material: 'PEEK',
//         H: 12,
//         L: 18,
//         W: 40,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLOUT',
//         type: '18OUT',
//         partNumber: '6914845',
//         description: 'CoRoent® XL, 14x18x45mm',
//         material: 'PEEK',
//         H: 14,
//         L: 18,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLOUT',
//         type: '18OUT',
//         partNumber: '6914850',
//         description: 'CoRoent® XL, 14x18x50mm',
//         material: 'PEEK',
//         H: 14,
//         L: 18,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLOUT',
//         type: '18OUT',
//         partNumber: '6914855',
//         description: 'CoRoent® XL, 14x18x55mm',
//         material: 'PEEK',
//         H: 14,
//         L: 18,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLOUT',
//         type: '18OUT',
//         partNumber: '6914860',
//         description: 'CoRoent® XL, 14x18x60mm',
//         material: 'PEEK',
//         H: 14,
//         L: 18,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLOUT',
//         type: '18OUT',
//         partNumber: '6980840',
//         description: 'CoRoent® XL, 8x18x40mm 10°',
//         material: 'PEEK',
//         H: 8,
//         L: 18,
//         W: 40,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLOUT',
//         type: '18OUT',
//         partNumber: '6981040',
//         description: 'CoRoent® XL, 10x18x40mm 10°',
//         material: 'PEEK',
//         H: 10,
//         L: 18,
//         W: 40,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLOUT',
//         type: '18OUT',
//         partNumber: '6981240',
//         description: 'CoRoent® XL, 12x18x40mm 10°',
//         material: 'PEEK',
//         H: 12,
//         L: 18,
//         W: 40,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLOUT',
//         type: '18OUT',
//         partNumber: '6981445',
//         description: 'CoRoent® XL, 14x18x45mm 10°',
//         material: 'PEEK',
//         H: 14,
//         L: 18,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLOUT',
//         type: '18OUT',
//         partNumber: '6981450',
//         description: 'CoRoent® XL, 14x18x50mm 10°',
//         material: 'PEEK',
//         H: 14,
//         L: 18,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLOUT',
//         type: '18OUT',
//         partNumber: '6981455',
//         description: 'CoRoent® XL, 14x18x55mm 10°',
//         material: 'PEEK',
//         H: 14,
//         L: 18,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLOUT',
//         type: '18OUT',
//         partNumber: '6981460',
//         description: 'CoRoent® XL, 14x18x60mm 10°',
//         material: 'PEEK',
//         H: 14,
//         L: 18,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLW0MOV',
//         type: '22MOV0',
//         partNumber: '6908245',
//         description: 'CoRoent® XL Wide, 8x22x45mm',
//         material: 'PEEK',
//         H: 8,
//         L: 22,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW0MOV',
//         type: '22MOV0',
//         partNumber: '6908250',
//         description: 'CoRoent® XL Wide, 8x22x50mm',
//         material: 'PEEK',
//         H: 8,
//         L: 22,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW0MOV',
//         type: '22MOV0',
//         partNumber: '6908255',
//         description: 'CoRoent® XL Wide, 8x22x55mm',
//         material: 'PEEK',
//         H: 8,
//         L: 22,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW0MOV',
//         type: '22MOV0',
//         partNumber: '6908260',
//         description: 'CoRoent® XL Wide, 8x22x60mm',
//         material: 'PEEK',
//         H: 8,
//         L: 22,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW0MOV',
//         type: '22MOV0',
//         partNumber: '6910245',
//         description: 'CoRoent® XL Wide, 10x22x45mm',
//         material: 'PEEK',
//         H: 10,
//         L: 22,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW0MOV',
//         type: '22MOV0',
//         partNumber: '6910250',
//         description: 'CoRoent® XL Wide, 10x22x50mm',
//         material: 'PEEK',
//         H: 10,
//         L: 22,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW0MOV',
//         type: '22MOV0',
//         partNumber: '6910255',
//         description: 'CoRoent® XL Wide, 10x22x55mm',
//         material: 'PEEK',
//         H: 10,
//         L: 22,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW0MOV',
//         type: '22MOV0',
//         partNumber: '6910260',
//         description: 'CoRoent® XL Wide, 10x22x60mm',
//         material: 'PEEK',
//         H: 10,
//         L: 22,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW0MOV',
//         type: '22MOV0',
//         partNumber: '6912245',
//         description: 'CoRoent® XL Wide, 12x22x45mm',
//         material: 'PEEK',
//         H: 12,
//         L: 22,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW0MOV',
//         type: '22MOV0',
//         partNumber: '6912250',
//         description: 'CoRoent® XL Wide, 12x22x50mm',
//         material: 'PEEK',
//         H: 12,
//         L: 22,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW0MOV',
//         type: '22MOV0',
//         partNumber: '6912255',
//         description: 'CoRoent® XL Wide, 12x22x55mm',
//         material: 'PEEK',
//         H: 12,
//         L: 22,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW0MOV',
//         type: '22MOV0',
//         partNumber: '6912260',
//         description: 'CoRoent® XL Wide, 12x22x60mm',
//         material: 'PEEK',
//         H: 12,
//         L: 22,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW10MOV',
//         type: '22MOV10',
//         partNumber: '6920845',
//         description: 'CoRoent® XL Wide, 8x22x45mm Lordotic',
//         material: 'PEEK',
//         H: 8,
//         L: 22,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW10MOV',
//         type: '22MOV10',
//         partNumber: '6920850',
//         description: 'CoRoent® XL Wide, 8x22x50mm Lordotic',
//         material: 'PEEK',
//         H: 8,
//         L: 22,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW10MOV',
//         type: '22MOV10',
//         partNumber: '6920855',
//         description: 'CoRoent® XL Wide, 8x22x55mm Lordotic',
//         material: 'PEEK',
//         H: 8,
//         L: 22,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW10MOV',
//         type: '22MOV10',
//         partNumber: '6920860',
//         description: 'CoRoent® XL Wide, 8x22x60mm Lordotic',
//         material: 'PEEK',
//         H: 8,
//         L: 22,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW10MOV',
//         type: '22MOV10',
//         partNumber: '6921045',
//         description: 'CoRoent® XL Wide, 10x22x45mm Lordotic',
//         material: 'PEEK',
//         H: 10,
//         L: 22,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW10MOV',
//         type: '22MOV10',
//         partNumber: '6921050',
//         description: 'CoRoent® XL Wide, 10x22x50mm Lordotic',
//         material: 'PEEK',
//         H: 10,
//         L: 22,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW10MOV',
//         type: '22MOV10',
//         partNumber: '6921055',
//         description: 'CoRoent® XL Wide, 10x22x55mm Lordotic',
//         material: 'PEEK',
//         H: 10,
//         L: 22,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW10MOV',
//         type: '22MOV10',
//         partNumber: '6921060',
//         description: 'CoRoent® XL Wide, 10x22x60mm Lordotic',
//         material: 'PEEK',
//         H: 10,
//         L: 22,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW10MOV',
//         type: '22MOV10',
//         partNumber: '6921245',
//         description: 'CoRoent® XL Wide, 12x22x45mm Lordotic',
//         material: 'PEEK',
//         H: 12,
//         L: 22,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW10MOV',
//         type: '22MOV10',
//         partNumber: '6921250',
//         description: 'CoRoent® XL Wide, 12x22x50mm Lordotic',
//         material: 'PEEK',
//         H: 12,
//         L: 22,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW10MOV',
//         type: '22MOV10',
//         partNumber: '6921255',
//         description: 'CoRoent® XL Wide, 12x22x55mm Lordotic',
//         material: 'PEEK',
//         H: 12,
//         L: 22,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW10MOV',
//         type: '22MOV10',
//         partNumber: '6921260',
//         description: 'CoRoent® XL Wide, 12x22x60mm Lordotic',
//         material: 'PEEK',
//         H: 12,
//         L: 22,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW15MOV',
//         type: '22MOV15',
//         partNumber: '7150850',
//         description: '8x22x50, CoRoent® XLW 15°',
//         material: 'PEEK',
//         H: 8,
//         L: 22,
//         W: 50,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW15MOV',
//         type: '22MOV15',
//         partNumber: '7150855',
//         description: '8x22x55, CoRoent® XLW 15°',
//         material: 'PEEK',
//         H: 8,
//         L: 22,
//         W: 55,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW15MOV',
//         type: '22MOV15',
//         partNumber: '7150860',
//         description: '8x22x60, CoRoent® XLW 15°',
//         material: 'PEEK',
//         H: 8,
//         L: 22,
//         W: 60,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW15MOV',
//         type: '22MOV15',
//         partNumber: '7151050',
//         description: '10x22x50, CoRoent® XLW 15°',
//         material: 'PEEK',
//         H: 10,
//         L: 22,
//         W: 50,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW15MOV',
//         type: '22MOV15',
//         partNumber: '7151055',
//         description: '10x22x55, CoRoent® XLW 15°',
//         material: 'PEEK',
//         H: 10,
//         L: 22,
//         W: 55,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW15MOV',
//         type: '22MOV15',
//         partNumber: '7151060',
//         description: '10x22x60, CoRoent® XLW 15°',
//         material: 'PEEK',
//         H: 10,
//         L: 22,
//         W: 60,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW15MOV',
//         type: '22MOV15',
//         partNumber: '7151250',
//         description: '12x22x50, CoRoent® XLW 15°',
//         material: 'PEEK',
//         H: 12,
//         L: 22,
//         W: 50,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW15MOV',
//         type: '22MOV15',
//         partNumber: '7151255',
//         description: '12x22x55, CoRoent® XLW 15°',
//         material: 'PEEK',
//         H: 12,
//         L: 22,
//         W: 55,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW15MOV',
//         type: '22MOV15',
//         partNumber: '7151260',
//         description: '12x22x60, CoRoent® XLW 15°',
//         material: 'PEEK',
//         H: 12,
//         L: 22,
//         W: 60,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLW15MOV',
//         type: '22MOV15',
//         partNumber: '7151450',
//         description: '14x22x50, CoRoent® XLW 15°',
//         material: 'PEEK',
//         H: 14,
//         L: 22,
//         W: 50,
//         lordosis: 15,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLW15MOV',
//         type: '22MOV15',
//         partNumber: '7151455',
//         description: '14x22x55, CoRoent® XLW 15°',
//         material: 'PEEK',
//         H: 14,
//         L: 22,
//         W: 55,
//         lordosis: 15,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLW15MOV',
//         type: '22MOV15',
//         partNumber: '7151460',
//         description: '14x22x60, CoRoent® XLW 15°',
//         material: 'PEEK',
//         H: 14,
//         L: 22,
//         W: 60,
//         lordosis: 15,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWOUT',
//         type: '22OUT',
//         partNumber: '6914245',
//         description: 'CoRoent® XL Wide, 14x22x45mm',
//         material: 'PEEK',
//         H: 14,
//         L: 22,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWOUT',
//         type: '22OUT',
//         partNumber: '6914250',
//         description: 'CoRoent® XL Wide, 14x22x50mm',
//         material: 'PEEK',
//         H: 14,
//         L: 22,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWOUT',
//         type: '22OUT',
//         partNumber: '6914255',
//         description: 'CoRoent® XL Wide, 14x22x55mm',
//         material: 'PEEK',
//         H: 14,
//         L: 22,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWOUT',
//         type: '22OUT',
//         partNumber: '6914260',
//         description: 'CoRoent® XL Wide, 14x22x60mm',
//         material: 'PEEK',
//         H: 14,
//         L: 22,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWOUT',
//         type: '22OUT',
//         partNumber: '6916250',
//         description: 'CoRoent® XL Wide, 16x22x50mm',
//         material: 'PEEK',
//         H: 16,
//         L: 22,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWOUT',
//         type: '22OUT',
//         partNumber: '6916255',
//         description: 'CoRoent® XL Wide, 16x22x55mm',
//         material: 'PEEK',
//         H: 16,
//         L: 22,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWOUT',
//         type: '22OUT',
//         partNumber: '6921445',
//         description: 'CoRoent® XL Wide, 14x22x45mm Lordotic',
//         material: 'PEEK',
//         H: 14,
//         L: 22,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWOUT',
//         type: '22OUT',
//         partNumber: '6921450',
//         description: 'CoRoent® XL Wide, 14x22x50mm Lordotic',
//         material: 'PEEK',
//         H: 14,
//         L: 22,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWOUT',
//         type: '22OUT',
//         partNumber: '6921455',
//         description: 'CoRoent® XL Wide, 14x22x55mm Lordotic',
//         material: 'PEEK',
//         H: 14,
//         L: 22,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWOUT',
//         type: '22OUT',
//         partNumber: '6921460',
//         description: 'CoRoent® XL Wide, 14x22x60mm Lordotic',
//         material: 'PEEK',
//         H: 14,
//         L: 22,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWOUT',
//         type: '22OUT',
//         partNumber: '6921650',
//         description: 'CoRoent® XL Wide, 16x22x50mm Lordotic',
//         material: 'PEEK',
//         H: 16,
//         L: 22,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWOUT',
//         type: '22OUT',
//         partNumber: '6921655',
//         description: 'CoRoent® XL Wide, 16x22x55mm Lordotic',
//         material: 'PEEK',
//         H: 16,
//         L: 22,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXW0MOV',
//         type: '26MOV0',
//         partNumber: '6208045',
//         description: '8x26x45mm CoRoent XLXW',
//         material: 'PEEK',
//         H: 8,
//         L: 26,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW0MOV',
//         type: '26MOV0',
//         partNumber: '6208050',
//         description: '8x26x50mm CoRoent XLXW',
//         material: 'PEEK',
//         H: 8,
//         L: 26,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW0MOV',
//         type: '26MOV0',
//         partNumber: '6208055',
//         description: '8x26x55mm CoRoent XLXW',
//         material: 'PEEK',
//         H: 8,
//         L: 26,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW0MOV',
//         type: '26MOV0',
//         partNumber: '6208060',
//         description: '8x26x60mm CoRoent XLXW',
//         material: 'PEEK',
//         H: 8,
//         L: 26,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW0MOV',
//         type: '26MOV0',
//         partNumber: '6210045',
//         description: '10x26x45mm CoRoent XLXW',
//         material: 'PEEK',
//         H: 10,
//         L: 26,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW0MOV',
//         type: '26MOV0',
//         partNumber: '6210050',
//         description: '10x26x50mm CoRoent XLXW',
//         material: 'PEEK',
//         H: 10,
//         L: 26,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW0MOV',
//         type: '26MOV0',
//         partNumber: '6210055',
//         description: '10x26x55mm CoRoent XLXW',
//         material: 'PEEK',
//         H: 10,
//         L: 26,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW0MOV',
//         type: '26MOV0',
//         partNumber: '6210060',
//         description: '10x26x60mm CoRoent XLXW',
//         material: 'PEEK',
//         H: 10,
//         L: 26,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW0MOV',
//         type: '26MOV0',
//         partNumber: '6212045',
//         description: '12x26x45mm CoRoent XLXW',
//         material: 'PEEK',
//         H: 12,
//         L: 26,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW0MOV',
//         type: '26MOV0',
//         partNumber: '6212050',
//         description: '12x26x50mm CoRoent XLXW',
//         material: 'PEEK',
//         H: 12,
//         L: 26,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW0MOV',
//         type: '26MOV0',
//         partNumber: '6212055',
//         description: '12x26x55mm CoRoent XLXW',
//         material: 'PEEK',
//         H: 12,
//         L: 26,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW0MOV',
//         type: '26MOV0',
//         partNumber: '6212060',
//         description: '12x26x60mm CoRoent XLXW',
//         material: 'PEEK',
//         H: 12,
//         L: 26,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW10MOV',
//         type: '26MOV10',
//         partNumber: '6208145',
//         description: '8x26x45mm - 10° CoRoent XLXW',
//         material: 'PEEK',
//         H: 8,
//         L: 26,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW10MOV',
//         type: '26MOV10',
//         partNumber: '6208150',
//         description: '8x26x50mm - 10° CoRoent XLXW',
//         material: 'PEEK',
//         H: 8,
//         L: 26,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW10MOV',
//         type: '26MOV10',
//         partNumber: '6208155',
//         description: '8x26x55mm - 10° CoRoent XLXW',
//         material: 'PEEK',
//         H: 8,
//         L: 26,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW10MOV',
//         type: '26MOV10',
//         partNumber: '6208160',
//         description: '8x26x60mm - 10° CoRoent XLXW',
//         material: 'PEEK',
//         H: 8,
//         L: 26,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW10MOV',
//         type: '26MOV10',
//         partNumber: '6210145',
//         description: '10x26x45mm - 10° CoRoent XLXW',
//         material: 'PEEK',
//         H: 10,
//         L: 26,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW10MOV',
//         type: '26MOV10',
//         partNumber: '6210150',
//         description: '10x26x50mm - 10° CoRoent XLXW',
//         material: 'PEEK',
//         H: 10,
//         L: 26,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW10MOV',
//         type: '26MOV10',
//         partNumber: '6210155',
//         description: '10x26x55mm - 10° CoRoent XLXW',
//         material: 'PEEK',
//         H: 10,
//         L: 26,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW10MOV',
//         type: '26MOV10',
//         partNumber: '6210160',
//         description: '10x26x60mm - 10° CoRoent XLXW',
//         material: 'PEEK',
//         H: 10,
//         L: 26,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW10MOV',
//         type: '26MOV10',
//         partNumber: '6212145',
//         description: '12x26x45mm - 10° CoRoent XLXW',
//         material: 'PEEK',
//         H: 12,
//         L: 26,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW10MOV',
//         type: '26MOV10',
//         partNumber: '6212150',
//         description: '12x26x50mm - 10° CoRoent XLXW',
//         material: 'PEEK',
//         H: 12,
//         L: 26,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW10MOV',
//         type: '26MOV10',
//         partNumber: '6212155',
//         description: '12x26x55mm - 10° CoRoent XLXW',
//         material: 'PEEK',
//         H: 12,
//         L: 26,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXW10MOV',
//         type: '26MOV10',
//         partNumber: '6212160',
//         description: '12x26x60mm - 10° CoRoent XLXW',
//         material: 'PEEK',
//         H: 12,
//         L: 26,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWOUT',
//         type: '26OUT',
//         partNumber: '6214045',
//         description: '14x26x45mm CoRoent XLXW',
//         material: 'PEEK',
//         H: 14,
//         L: 26,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWOUT',
//         type: '26OUT',
//         partNumber: '6214050',
//         description: '14x26x50mm CoRoent XLXW',
//         material: 'PEEK',
//         H: 14,
//         L: 26,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWOUT',
//         type: '26OUT',
//         partNumber: '6214055',
//         description: '14x26x55mm CoRoent XLXW',
//         material: 'PEEK',
//         H: 14,
//         L: 26,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWOUT',
//         type: '26OUT',
//         partNumber: '6214060',
//         description: '14x26x60mm CoRoent XLXW',
//         material: 'PEEK',
//         H: 14,
//         L: 26,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWOUT',
//         type: '26OUT',
//         partNumber: '6214145',
//         description: '14x26x45mm - 10° CoRoent XLXW',
//         material: 'PEEK',
//         H: 14,
//         L: 26,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWOUT',
//         type: '26OUT',
//         partNumber: '6214150',
//         description: '14x26x50mm - 10° CoRoent XLXW',
//         material: 'PEEK',
//         H: 14,
//         L: 26,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWOUT',
//         type: '26OUT',
//         partNumber: '6214155',
//         description: '14x26x55mm - 10° CoRoent XLXW',
//         material: 'PEEK',
//         H: 14,
//         L: 26,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWOUT',
//         type: '26OUT',
//         partNumber: '6214160',
//         description: '14x26x60mm - 10° CoRoent XLXW',
//         material: 'PEEK',
//         H: 14,
//         L: 26,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLTIC18MOV0',
//         type: '18MOV0',
//         partNumber: '6008845CP2',
//         description: 'CoRoent® XL+ Ti-C, 8x18x45mm',
//         material: 'TIC',
//         H: 8,
//         L: 18,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV0',
//         type: '18MOV0',
//         partNumber: '6008850CP2',
//         description: 'CoRoent® XL+ Ti-C, 8x18x50mm',
//         material: 'TIC',
//         H: 8,
//         L: 18,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV0',
//         type: '18MOV0',
//         partNumber: '6008855CP2',
//         description: 'CoRoent® XL+ Ti-C, 8x18x55mm',
//         material: 'TIC',
//         H: 8,
//         L: 18,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV0',
//         type: '18MOV0',
//         partNumber: '6008860CP2',
//         description: 'CoRoent® XL+ Ti-C, 8x18x60mm',
//         material: 'TIC',
//         H: 8,
//         L: 18,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV0',
//         type: '18MOV0',
//         partNumber: '6010845CP2',
//         description: 'CoRoent® XL+ Ti-C, 10x18x45mm',
//         material: 'TIC',
//         H: 10,
//         L: 18,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV0',
//         type: '18MOV0',
//         partNumber: '6010850CP2',
//         description: 'CoRoent® XL+ Ti-C, 10x18x50mm',
//         material: 'TIC',
//         H: 10,
//         L: 18,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV0',
//         type: '18MOV0',
//         partNumber: '6010855CP2',
//         description: 'CoRoent® XL+ Ti-C, 10x18x55mm',
//         material: 'TIC',
//         H: 10,
//         L: 18,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV0',
//         type: '18MOV0',
//         partNumber: '6010860CP2',
//         description: 'CoRoent® XL+ Ti-C, 10x18x60mm',
//         material: 'TIC',
//         H: 10,
//         L: 18,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV0',
//         type: '18MOV0',
//         partNumber: '6912845CP2',
//         description: 'CoRoent® XL Ti-C, 12x18x45mm',
//         material: 'TIC',
//         H: 12,
//         L: 18,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV0',
//         type: '18MOV0',
//         partNumber: '6912850CP2',
//         description: 'CoRoent® XL Ti-C, 12x18x50mm',
//         material: 'TIC',
//         H: 12,
//         L: 18,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV0',
//         type: '18MOV0',
//         partNumber: '6912855CP2',
//         description: 'CoRoent® XL Ti-C, 12x18x55mm',
//         material: 'TIC',
//         H: 12,
//         L: 18,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV0',
//         type: '18MOV0',
//         partNumber: '6912860CP2',
//         description: 'CoRoent® XL Ti-C, 12x18x60mm',
//         material: 'TIC',
//         H: 12,
//         L: 18,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV10',
//         type: '18MOV10',
//         partNumber: '6308845CP2',
//         description: 'CoRoent® XL+ Ti-C, 8x18x45mm 10°',
//         material: 'TIC',
//         H: 8,
//         L: 18,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV10',
//         type: '18MOV10',
//         partNumber: '6308850CP2',
//         description: 'CoRoent® XL+ Ti-C, 8x18x50mm 10°',
//         material: 'TIC',
//         H: 8,
//         L: 18,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV10',
//         type: '18MOV10',
//         partNumber: '6308855CP2',
//         description: 'CoRoent® XL+ Ti-C, 8x18x55mm 10°',
//         material: 'TIC',
//         H: 8,
//         L: 18,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV10',
//         type: '18MOV10',
//         partNumber: '6308860CP2',
//         description: 'CoRoent® XL+ Ti-C, 8x18x60mm 10°',
//         material: 'TIC',
//         H: 8,
//         L: 18,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV10',
//         type: '18MOV10',
//         partNumber: '6310845CP2',
//         description: 'CoRoent® XL+ Ti-C, 10x18x45mm 10°',
//         material: 'TIC',
//         H: 10,
//         L: 18,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV10',
//         type: '18MOV10',
//         partNumber: '6310850CP2',
//         description: 'CoRoent® XL+ Ti-C, 10x18x50mm 10°',
//         material: 'TIC',
//         H: 10,
//         L: 18,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV10',
//         type: '18MOV10',
//         partNumber: '6310855CP2',
//         description: 'CoRoent® XL+ Ti-C, 10x18x55mm 10°',
//         material: 'TIC',
//         H: 10,
//         L: 18,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV10',
//         type: '18MOV10',
//         partNumber: '6310860CP2',
//         description: 'CoRoent® XL+ Ti-C, 10x18x60mm 10°',
//         material: 'TIC',
//         H: 10,
//         L: 18,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV10',
//         type: '18MOV10',
//         partNumber: '6981245CP2',
//         description: 'CoRoent® XL Ti-C, 12x18x45mm 10°',
//         material: 'TIC',
//         H: 12,
//         L: 18,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV10',
//         type: '18MOV10',
//         partNumber: '6981250CP2',
//         description: 'CoRoent® XL Ti-C, 12x18x50mm 10°',
//         material: 'TIC',
//         H: 12,
//         L: 18,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV10',
//         type: '18MOV10',
//         partNumber: '6981255CP2',
//         description: 'CoRoent® XL Ti-C, 12x18x55mm 10°',
//         material: 'TIC',
//         H: 12,
//         L: 18,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18MOV10',
//         type: '18MOV10',
//         partNumber: '6981260CP2',
//         description: 'CoRoent® XL Ti-C, 12x18x60mm 10°',
//         material: 'TIC',
//         H: 12,
//         L: 18,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLTIC18OUT',
//         type: '18OUT',
//         partNumber: '6008840CP2',
//         description: 'CoRoent® XL+ Ti-C, 8x18x40mm',
//         material: 'TIC',
//         H: 8,
//         L: 18,
//         W: 40,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLTIC18OUT',
//         type: '18OUT',
//         partNumber: '6010840CP2',
//         description: 'CoRoent® XL+ Ti-C, 10x18x40mm',
//         material: 'TIC',
//         H: 10,
//         L: 18,
//         W: 40,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLTIC18OUT',
//         type: '18OUT',
//         partNumber: '6912840CP2',
//         description: 'CoRoent® XL Ti-C, 12x18x40mm',
//         material: 'TIC',
//         H: 12,
//         L: 18,
//         W: 40,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLTIC18OUT',
//         type: '18OUT',
//         partNumber: '6914845CP2',
//         description: 'CoRoent® XL Ti-C, 14x18x45mm',
//         material: 'TIC',
//         H: 14,
//         L: 18,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLTIC18OUT',
//         type: '18OUT',
//         partNumber: '6914850CP2',
//         description: 'CoRoent® XL Ti-C, 14x18x50mm',
//         material: 'TIC',
//         H: 14,
//         L: 18,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLTIC18OUT',
//         type: '18OUT',
//         partNumber: '6914855CP2',
//         description: 'CoRoent® XL Ti-C, 14x18x55mm',
//         material: 'TIC',
//         H: 14,
//         L: 18,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLTIC18OUT',
//         type: '18OUT',
//         partNumber: '6914860CP2',
//         description: 'CoRoent® XL Ti-C, 14x18x60mm',
//         material: 'TIC',
//         H: 14,
//         L: 18,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLTIC18OUT',
//         type: '18OUT',
//         partNumber: '6308840CP2',
//         description: 'CoRoent® XL+ Ti-C, 8x18x40mm 10°',
//         material: 'TIC',
//         H: 8,
//         L: 18,
//         W: 40,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLTIC18OUT',
//         type: '18OUT',
//         partNumber: '6310840CP2',
//         description: 'CoRoent® XL+ Ti-C, 10x18x40mm 10°',
//         material: 'TIC',
//         H: 10,
//         L: 18,
//         W: 40,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLTIC18OUT',
//         type: '18OUT',
//         partNumber: '6981240CP2',
//         description: 'CoRoent® XL Ti-C, 12x18x40mm 10°',
//         material: 'TIC',
//         H: 12,
//         L: 18,
//         W: 40,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLTIC18OUT',
//         type: '18OUT',
//         partNumber: '6981445CP2',
//         description: 'CoRoent® XL Ti-C, 14x18x45mm 10°',
//         material: 'TIC',
//         H: 14,
//         L: 18,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLTIC18OUT',
//         type: '18OUT',
//         partNumber: '6981450CP2',
//         description: 'CoRoent® XL Ti-C, 14x18x50mm 10°',
//         material: 'TIC',
//         H: 14,
//         L: 18,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLTIC18OUT',
//         type: '18OUT',
//         partNumber: '6981455CP2',
//         description: 'CoRoent® XL Ti-C, 14x18x55mm 10°',
//         material: 'TIC',
//         H: 14,
//         L: 18,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLTIC18OUT',
//         type: '18OUT',
//         partNumber: '6981460CP2',
//         description: 'CoRoent® XL Ti-C, 14x18x60mm 10°',
//         material: 'TIC',
//         H: 14,
//         L: 18,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWTIC22MOV0',
//         type: '22MOV0',
//         partNumber: '6508245CP2',
//         description: 'CoRoent® XL+ Wide Ti-C, 8x22x45mm',
//         material: 'TIC',
//         H: 8,
//         L: 22,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV0',
//         type: '22MOV0',
//         partNumber: '6508250CP2',
//         description: 'CoRoent® XL+ Wide Ti-C, 8x22x50mm',
//         material: 'TIC',
//         H: 8,
//         L: 22,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV0',
//         type: '22MOV0',
//         partNumber: '6508255CP2',
//         description: 'CoRoent® XL+ Wide Ti-C, 8x22x55mm',
//         material: 'TIC',
//         H: 8,
//         L: 22,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV0',
//         type: '22MOV0',
//         partNumber: '6508260CP2',
//         description: 'CoRoent® XL+ Wide Ti-C, 8x22x60mm',
//         material: 'TIC',
//         H: 8,
//         L: 22,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV0',
//         type: '22MOV0',
//         partNumber: '6510245CP2',
//         description: 'CoRoent® XL+ Wide Ti-C, 10x22x45mm',
//         material: 'TIC',
//         H: 10,
//         L: 22,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV0',
//         type: '22MOV0',
//         partNumber: '6510250CP2',
//         description: 'CoRoent® XL+ Wide Ti-C, 10x22x50mm',
//         material: 'TIC',
//         H: 10,
//         L: 22,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV0',
//         type: '22MOV0',
//         partNumber: '6510255CP2',
//         description: 'CoRoent® XL+ Wide Ti-C, 10x22x55mm',
//         material: 'TIC',
//         H: 10,
//         L: 22,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV0',
//         type: '22MOV0',
//         partNumber: '6510260CP2',
//         description: 'CoRoent® XL+ Wide Ti-C, 10x22x60mm',
//         material: 'TIC',
//         H: 10,
//         L: 22,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV0',
//         type: '22MOV0',
//         partNumber: '6912245CP2',
//         description: 'CoRoent® XL Wide Ti-C, 12x22x45mm',
//         material: 'TIC',
//         H: 12,
//         L: 22,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV0',
//         type: '22MOV0',
//         partNumber: '6912250CP2',
//         description: 'CoRoent® XL Wide Ti-C, 12x22x50mm',
//         material: 'TIC',
//         H: 12,
//         L: 22,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV0',
//         type: '22MOV0',
//         partNumber: '6912255CP2',
//         description: 'CoRoent® XL Wide Ti-C, 12x22x55mm',
//         material: 'TIC',
//         H: 12,
//         L: 22,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV0',
//         type: '22MOV0',
//         partNumber: '6912260CP2',
//         description: 'CoRoent® XL Wide Ti-C, 12x22x60mm',
//         material: 'TIC',
//         H: 12,
//         L: 22,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV10',
//         type: '22MOV10',
//         partNumber: '6308245CP2',
//         description: 'CoRoent® XL+ Wide Ti-C, 8x22x45mm Lordotic',
//         material: 'TIC',
//         H: 8,
//         L: 22,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV10',
//         type: '22MOV10',
//         partNumber: '6308250CP2',
//         description: 'CoRoent® XL+ Wide Ti-C, 8x22x50mm Lordotic',
//         material: 'TIC',
//         H: 8,
//         L: 22,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV10',
//         type: '22MOV10',
//         partNumber: '6308255CP2',
//         description: 'CoRoent® XL+ Wide Ti-C, 8x22x55mm Lordotic',
//         material: 'TIC',
//         H: 8,
//         L: 22,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV10',
//         type: '22MOV10',
//         partNumber: '6308260CP2',
//         description: 'CoRoent® XL+ Wide Ti-C, 8x22x60mm Lordotic',
//         material: 'TIC',
//         H: 8,
//         L: 22,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV10',
//         type: '22MOV10',
//         partNumber: '6310245CP2',
//         description: 'CoRoent® XL+ Wide Ti-C, 10x22x45mm Lordotic',
//         material: 'TIC',
//         H: 10,
//         L: 22,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV10',
//         type: '22MOV10',
//         partNumber: '6310250CP2',
//         description: 'CoRoent® XL+ Wide Ti-C, 10x22x50mm Lordotic',
//         material: 'TIC',
//         H: 10,
//         L: 22,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV10',
//         type: '22MOV10',
//         partNumber: '6310255CP2',
//         description: 'CoRoent® XL+ Wide Ti-C, 10x22x55mm Lordotic',
//         material: 'TIC',
//         H: 10,
//         L: 22,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV10',
//         type: '22MOV10',
//         partNumber: '6310260CP2',
//         description: 'CoRoent® XL+ Wide Ti-C, 10x22x60mm Lordotic',
//         material: 'TIC',
//         H: 10,
//         L: 22,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV10',
//         type: '22MOV10',
//         partNumber: '6921245CP2',
//         description: 'CoRoent® XL Wide Ti-C, 12x22x45mm Lordotic',
//         material: 'TIC',
//         H: 12,
//         L: 22,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV10',
//         type: '22MOV10',
//         partNumber: '6921250CP2',
//         description: 'CoRoent® XL Wide Ti-C, 12x22x50mm Lordotic',
//         material: 'TIC',
//         H: 12,
//         L: 22,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV10',
//         type: '22MOV10',
//         partNumber: '6921255CP2',
//         description: 'CoRoent® XL Wide Ti-C, 12x22x55mm Lordotic',
//         material: 'TIC',
//         H: 12,
//         L: 22,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV10',
//         type: '22MOV10',
//         partNumber: '6921260CP2',
//         description: 'CoRoent® XL Wide Ti-C, 12x22x60mm Lordotic',
//         material: 'TIC',
//         H: 12,
//         L: 22,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV15',
//         type: '22MOV15',
//         partNumber: '7150850CP2',
//         description: '8x22x50, CoRoent® XLW Ti-C 15°',
//         material: 'TIC',
//         H: 8,
//         L: 22,
//         W: 50,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV15',
//         type: '22MOV15',
//         partNumber: '7150855CP2',
//         description: '8x22x55, CoRoent® XLW Ti-C 15°',
//         material: 'TIC',
//         H: 8,
//         L: 22,
//         W: 55,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV15',
//         type: '22MOV15',
//         partNumber: '7150860CP2',
//         description: '8x22x60, CoRoent® XLW Ti-C 15°',
//         material: 'TIC',
//         H: 8,
//         L: 22,
//         W: 60,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV15',
//         type: '22MOV15',
//         partNumber: '7151050CP2',
//         description: '10x22x50, CoRoent® XLW Ti-C 15°',
//         material: 'TIC',
//         H: 10,
//         L: 22,
//         W: 50,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV15',
//         type: '22MOV15',
//         partNumber: '7151055CP2',
//         description: '10x22x55, CoRoent® XLW Ti-C 15°',
//         material: 'TIC',
//         H: 10,
//         L: 22,
//         W: 55,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV15',
//         type: '22MOV15',
//         partNumber: '7151060CP2',
//         description: '10x22x60, CoRoent® XLW Ti-C 15°',
//         material: 'TIC',
//         H: 10,
//         L: 22,
//         W: 60,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV15',
//         type: '22MOV15',
//         partNumber: '7151250CP2',
//         description: '12x22x50, CoRoent® XLW Ti-C 15°',
//         material: 'TIC',
//         H: 12,
//         L: 22,
//         W: 50,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV15',
//         type: '22MOV15',
//         partNumber: '7151255CP2',
//         description: '12x22x55, CoRoent® XLW Ti-C 15°',
//         material: 'TIC',
//         H: 12,
//         L: 22,
//         W: 55,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV15',
//         type: '22MOV15',
//         partNumber: '7151260CP2',
//         description: '12x22x60, CoRoent® XLW Ti-C 15°',
//         material: 'TIC',
//         H: 12,
//         L: 22,
//         W: 60,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLWTIC22MOV15',
//         type: '22MOV15',
//         partNumber: '7151450CP2',
//         description: '14x22x50, CoRoent® XLW Ti-C 15°',
//         material: 'TIC',
//         H: 14,
//         L: 22,
//         W: 50,
//         lordosis: 15,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWTIC22MOV15',
//         type: '22MOV15',
//         partNumber: '7151455CP2',
//         description: '14x22x55, CoRoent® XLW Ti-C 15°',
//         material: 'TIC',
//         H: 14,
//         L: 22,
//         W: 55,
//         lordosis: 15,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWTIC22MOV15',
//         type: '22MOV15',
//         partNumber: '7151460CP2',
//         description: '14x22x60, CoRoent® XLW Ti-C 15°',
//         material: 'TIC',
//         H: 14,
//         L: 22,
//         W: 60,
//         lordosis: 15,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWTIC22OUT',
//         type: '22OUT',
//         partNumber: '6914245CP2',
//         description: 'CoRoent® XL Wide Ti-C, 14x22x45mm',
//         material: 'TIC',
//         H: 14,
//         L: 22,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWTIC22OUT',
//         type: '22OUT',
//         partNumber: '6914250CP2',
//         description: 'CoRoent® XL Wide Ti-C, 14x22x50mm',
//         material: 'TIC',
//         H: 14,
//         L: 22,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWTIC22OUT',
//         type: '22OUT',
//         partNumber: '6914255CP2',
//         description: 'CoRoent® XL Wide Ti-C, 14x22x55mm',
//         material: 'TIC',
//         H: 14,
//         L: 22,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWTIC22OUT',
//         type: '22OUT',
//         partNumber: '6914260CP2',
//         description: 'CoRoent® XL Wide Ti-C, 14x22x60mm',
//         material: 'TIC',
//         H: 14,
//         L: 22,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWTIC22OUT',
//         type: '22OUT',
//         partNumber: '6916250CP2',
//         description: 'CoRoent® XL Wide Ti-C, 16x22x50mm',
//         material: 'TIC',
//         H: 16,
//         L: 22,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWTIC22OUT',
//         type: '22OUT',
//         partNumber: '6916255CP2',
//         description: 'CoRoent® XL Wide Ti-C, 16x22x55mm',
//         material: 'TIC',
//         H: 16,
//         L: 22,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWTIC22OUT',
//         type: '22OUT',
//         partNumber: '6921445CP2',
//         description: 'CoRoent® XL Wide Ti-C, 14x22x45mm Lordotic',
//         material: 'TIC',
//         H: 14,
//         L: 22,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWTIC22OUT',
//         type: '22OUT',
//         partNumber: '6921450CP2',
//         description: 'CoRoent® XL Wide Ti-C, 14x22x50mm Lordotic',
//         material: 'TIC',
//         H: 14,
//         L: 22,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWTIC22OUT',
//         type: '22OUT',
//         partNumber: '6921455CP2',
//         description: 'CoRoent® XL Wide Ti-C, 14x22x55mm Lordotic',
//         material: 'TIC',
//         H: 14,
//         L: 22,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWTIC22OUT',
//         type: '22OUT',
//         partNumber: '6921460CP2',
//         description: 'CoRoent® XL Wide Ti-C, 14x22x60mm Lordotic',
//         material: 'TIC',
//         H: 14,
//         L: 22,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWTIC22OUT',
//         type: '22OUT',
//         partNumber: '6921650CP2',
//         description: 'CoRoent® XL Wide Ti-C, 16x22x50mm Lordotic',
//         material: 'TIC',
//         H: 16,
//         L: 22,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLWTIC22OUT',
//         type: '22OUT',
//         partNumber: '6921655CP2',
//         description: 'CoRoent® XL Wide Ti-C, 16x22x55mm Lordotic',
//         material: 'TIC',
//         H: 16,
//         L: 22,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWTIC26MOV0',
//         type: '26MOV0',
//         partNumber: '6208045CP2',
//         description: '8x26x45mm CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 8,
//         L: 26,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWTIC26MOV0',
//         type: '26MOV0',
//         partNumber: '6208050CP2',
//         description: '8x26x50mm CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 8,
//         L: 26,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWTIC26MOV0',
//         type: '26MOV0',
//         partNumber: '6208055CP2',
//         description: '8x26x55mm CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 8,
//         L: 26,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26MOV0',
//         type: '26MOV0',
//         partNumber: '6208060CP2',
//         description: '8x26x60mm CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 8,
//         L: 26,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWTIC26MOV0',
//         type: '26MOV0',
//         partNumber: '6210045CP2',
//         description: '10x26x45mm CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 10,
//         L: 26,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26MOV0',
//         type: '26MOV0',
//         partNumber: '6210050CP2',
//         description: '10x26x50mm CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 10,
//         L: 26,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26MOV0',
//         type: '26MOV0',
//         partNumber: '6210055CP2',
//         description: '10x26x55mm CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 10,
//         L: 26,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26MOV0',
//         type: '26MOV0',
//         partNumber: '6210060CP2',
//         description: '10x26x60mm CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 10,
//         L: 26,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26MOV0',
//         type: '26MOV0',
//         partNumber: '6212045CP2',
//         description: '12x26x45mm CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 12,
//         L: 26,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWTIC26MOV0',
//         type: '26MOV0',
//         partNumber: '6212050CP2',
//         description: '12x26x50mm CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 12,
//         L: 26,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWTIC26MOV0',
//         type: '26MOV0',
//         partNumber: '6212055CP2',
//         description: '12x26x55mm CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 12,
//         L: 26,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26MOV0',
//         type: '26MOV0',
//         partNumber: '6212060CP2',
//         description: '12x26x60mm CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 12,
//         L: 26,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26MOV10',
//         type: '26MOV10',
//         partNumber: '6208145CP2',
//         description: '8x26x45mm - 10° CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 8,
//         L: 26,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26MOV10',
//         type: '26MOV10',
//         partNumber: '6208150CP2',
//         description: '8x26x50mm - 10° CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 8,
//         L: 26,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26MOV10',
//         type: '26MOV10',
//         partNumber: '6208155CP2',
//         description: '8x26x55mm - 10° CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 8,
//         L: 26,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26MOV10',
//         type: '26MOV10',
//         partNumber: '6208160CP2',
//         description: '8x26x60mm - 10° CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 8,
//         L: 26,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26MOV10',
//         type: '26MOV10',
//         partNumber: '6210145CP2',
//         description: '10x26x45mm - 10° CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 10,
//         L: 26,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26MOV10',
//         type: '26MOV10',
//         partNumber: '6210150CP2',
//         description: '10x26x50mm - 10° CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 10,
//         L: 26,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26MOV10',
//         type: '26MOV10',
//         partNumber: '6210155CP2',
//         description: '10x26x55mm - 10° CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 10,
//         L: 26,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26MOV10',
//         type: '26MOV10',
//         partNumber: '6210160CP2',
//         description: '10x26x60mm - 10° CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 10,
//         L: 26,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26MOV10',
//         type: '26MOV10',
//         partNumber: '6212145CP2',
//         description: '12x26x45mm - 10° CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 12,
//         L: 26,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWTIC26MOV10',
//         type: '26MOV10',
//         partNumber: '6212150CP2',
//         description: '12x26x50mm - 10° CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 12,
//         L: 26,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26MOV10',
//         type: '26MOV10',
//         partNumber: '6212155CP2',
//         description: '12x26x55mm - 10° CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 12,
//         L: 26,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26MOV10',
//         type: '26MOV10',
//         partNumber: '6212160CP2',
//         description: '12x26x60mm - 10° CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 12,
//         L: 26,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'CORXLXWTIC26OUT',
//         type: '26OUT',
//         partNumber: '6214045CP2',
//         description: '14x26x45mm CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 14,
//         L: 26,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWTIC26OUT',
//         type: '26OUT',
//         partNumber: '6214050CP2',
//         description: '14x26x50mm CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 14,
//         L: 26,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWTIC26OUT',
//         type: '26OUT',
//         partNumber: '6214055CP2',
//         description: '14x26x55mm CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 14,
//         L: 26,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWTIC26OUT',
//         type: '26OUT',
//         partNumber: '6214060CP2',
//         description: '14x26x60mm CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 14,
//         L: 26,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWTIC26OUT',
//         type: '26OUT',
//         partNumber: '6214145CP2',
//         description: '14x26x45mm - 10° CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 14,
//         L: 26,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWTIC26OUT',
//         type: '26OUT',
//         partNumber: '6214150CP2',
//         description: '14x26x50mm - 10° CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 14,
//         L: 26,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWTIC26OUT',
//         type: '26OUT',
//         partNumber: '6214155CP2',
//         description: '14x26x55mm - 10° CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 14,
//         L: 26,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'CORXLXWTIC26OUT',
//         type: '26OUT',
//         partNumber: '6214160CP2',
//         description: '14x26x60mm - 10° CoRoent XLXW Ti-C',
//         material: 'TIC',
//         H: 14,
//         L: 26,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 1
//     },
//     {
//         setType: 'MDLUSXL0',
//         type: '18MOV0',
//         partNumber: '1180845P2',
//         description: 'XLIF 3D 8x18x45mm - 0°',
//         material: 'MODULUS',
//         H: 8,
//         L: 18,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL0',
//         type: '18MOV0',
//         partNumber: '1180850P2',
//         description: 'XLIF 3D 8x18x50mm - 0°',
//         material: 'MODULUS',
//         H: 8,
//         L: 18,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL0',
//         type: '18MOV0',
//         partNumber: '1180855P2',
//         description: 'XLIF 3D 8x18x55mm - 0°',
//         material: 'MODULUS',
//         H: 8,
//         L: 18,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL0',
//         type: '18MOV0',
//         partNumber: '1180860P2',
//         description: 'XLIF 3D 8x18x60mm - 0°',
//         material: 'MODULUS',
//         H: 8,
//         L: 18,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL0',
//         type: '18MOV0',
//         partNumber: '1180045P2',
//         description: 'XLIF 3D 10x18x45mm - 0°',
//         material: 'MODULUS',
//         H: 10,
//         L: 18,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL0',
//         type: '18MOV0',
//         partNumber: '1180050P2',
//         description: 'XLIF 3D 10x18x50mm - 0°',
//         material: 'MODULUS',
//         H: 10,
//         L: 18,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL0',
//         type: '18MOV0',
//         partNumber: '1180055P2',
//         description: 'XLIF 3D 10x18x55mm - 0°',
//         material: 'MODULUS',
//         H: 10,
//         L: 18,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL0',
//         type: '18MOV0',
//         partNumber: '1180060P2',
//         description: 'XLIF 3D 10x18x60mm - 0°',
//         material: 'MODULUS',
//         H: 10,
//         L: 18,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL0',
//         type: '18MOV0',
//         partNumber: '1180245P2',
//         description: 'XLIF 3D 12x18x45mm - 0°',
//         material: 'MODULUS',
//         H: 12,
//         L: 18,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL0',
//         type: '18MOV0',
//         partNumber: '1180250P2',
//         description: 'XLIF 3D 12x18x50mm - 0°',
//         material: 'MODULUS',
//         H: 12,
//         L: 18,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL0',
//         type: '18MOV0',
//         partNumber: '1180255P2',
//         description: 'XLIF 3D 12x18x55mm - 0°',
//         material: 'MODULUS',
//         H: 12,
//         L: 18,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL0',
//         type: '18MOV0',
//         partNumber: '1180260P2',
//         description: 'XLIF 3D 12x18x60mm - 0°',
//         material: 'MODULUS',
//         H: 12,
//         L: 18,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL10',
//         type: '18MOV10',
//         partNumber: '1181845P2',
//         description: 'XLIF 3D 8x18x45mm - 10°',
//         material: 'MODULUS',
//         H: 8,
//         L: 18,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL10',
//         type: '18MOV10',
//         partNumber: '1181850P2',
//         description: 'XLIF 3D 8x18x50mm - 10°',
//         material: 'MODULUS',
//         H: 8,
//         L: 18,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL10',
//         type: '18MOV10',
//         partNumber: '1181855P2',
//         description: 'XLIF 3D 8x18x55mm - 10°',
//         material: 'MODULUS',
//         H: 8,
//         L: 18,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL10',
//         type: '18MOV10',
//         partNumber: '1181860P2',
//         description: 'XLIF 3D 8x18x60mm - 10°',
//         material: 'MODULUS',
//         H: 8,
//         L: 18,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL10',
//         type: '18MOV10',
//         partNumber: '1181045P2',
//         description: 'XLIF 3D 10x18x45mm - 10°',
//         material: 'MODULUS',
//         H: 10,
//         L: 18,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL10',
//         type: '18MOV10',
//         partNumber: '1181050P2',
//         description: 'XLIF 3D 10x18x50mm - 10°',
//         material: 'MODULUS',
//         H: 10,
//         L: 18,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL10',
//         type: '18MOV10',
//         partNumber: '1181055P2',
//         description: 'XLIF 3D 10x18x55mm - 10°',
//         material: 'MODULUS',
//         H: 10,
//         L: 18,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL10',
//         type: '18MOV10',
//         partNumber: '1181060P2',
//         description: 'XLIF 3D 10x18x60mm - 10°',
//         material: 'MODULUS',
//         H: 10,
//         L: 18,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL10',
//         type: '18MOV10',
//         partNumber: '1181245P2',
//         description: 'XLIF 3D 12x18x45mm - 10°',
//         material: 'MODULUS',
//         H: 12,
//         L: 18,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL10',
//         type: '18MOV10',
//         partNumber: '1181250P2',
//         description: 'XLIF 3D 12x18x50mm - 10°',
//         material: 'MODULUS',
//         H: 12,
//         L: 18,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL10',
//         type: '18MOV10',
//         partNumber: '1181255P2',
//         description: 'XLIF 3D 12x18x55mm - 10°',
//         material: 'MODULUS',
//         H: 12,
//         L: 18,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXL10',
//         type: '18MOV10',
//         partNumber: '1181260P2',
//         description: 'XLIF 3D 12x18x60mm - 10°',
//         material: 'MODULUS',
//         H: 12,
//         L: 18,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW0',
//         type: '22MOV0',
//         partNumber: '1220845P2',
//         description: 'XLIF 3D 8x22x45mm - 0°',
//         material: 'MODULUS',
//         H: 8,
//         L: 22,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW0',
//         type: '22MOV0',
//         partNumber: '1220850P2',
//         description: 'XLIF 3D 8x22x50mm - 0°',
//         material: 'MODULUS',
//         H: 8,
//         L: 22,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW0',
//         type: '22MOV0',
//         partNumber: '1220855P2',
//         description: 'XLIF 3D 8x22x55mm - 0°',
//         material: 'MODULUS',
//         H: 8,
//         L: 22,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW0',
//         type: '22MOV0',
//         partNumber: '1220860P2',
//         description: 'XLIF 3D 8x22x60mm - 0°',
//         material: 'MODULUS',
//         H: 8,
//         L: 22,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW0',
//         type: '22MOV0',
//         partNumber: '1220045P2',
//         description: 'XLIF 3D 10x22x45mm - 0°',
//         material: 'MODULUS',
//         H: 10,
//         L: 22,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW0',
//         type: '22MOV0',
//         partNumber: '1220050P2',
//         description: 'XLIF 3D 10x22x50mm - 0°',
//         material: 'MODULUS',
//         H: 10,
//         L: 22,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW0',
//         type: '22MOV0',
//         partNumber: '1220055P2',
//         description: 'XLIF 3D 10x22x55mm - 0°',
//         material: 'MODULUS',
//         H: 10,
//         L: 22,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW0',
//         type: '22MOV0',
//         partNumber: '1220060P2',
//         description: 'XLIF 3D 10x22x60mm - 0°',
//         material: 'MODULUS',
//         H: 10,
//         L: 22,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW0',
//         type: '22MOV0',
//         partNumber: '1220245P2',
//         description: 'XLIF 3D 12x22x45mm - 0°',
//         material: 'MODULUS',
//         H: 12,
//         L: 22,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW0',
//         type: '22MOV0',
//         partNumber: '1220250P2',
//         description: 'XLIF 3D 12x22x50mm - 0°',
//         material: 'MODULUS',
//         H: 12,
//         L: 22,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW0',
//         type: '22MOV0',
//         partNumber: '1220255P2',
//         description: 'XLIF 3D 12x22x55mm - 0°',
//         material: 'MODULUS',
//         H: 12,
//         L: 22,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW0',
//         type: '22MOV0',
//         partNumber: '1220260P2',
//         description: 'XLIF 3D 12x22x60mm - 0°',
//         material: 'MODULUS',
//         H: 12,
//         L: 22,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW10',
//         type: '22MOV10',
//         partNumber: '1221845P2',
//         description: 'XLIF 3D 8x22x45mm - 10°',
//         material: 'MODULUS',
//         H: 8,
//         L: 22,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW10',
//         type: '22MOV10',
//         partNumber: '1221850P2',
//         description: 'XLIF 3D 8x22x50mm - 10°',
//         material: 'MODULUS',
//         H: 8,
//         L: 22,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW10',
//         type: '22MOV10',
//         partNumber: '1221855P2',
//         description: 'XLIF 3D 8x22x55mm - 10°',
//         material: 'MODULUS',
//         H: 8,
//         L: 22,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW10',
//         type: '22MOV10',
//         partNumber: '1221860P2',
//         description: 'XLIF 3D 8x22x60mm - 10°',
//         material: 'MODULUS',
//         H: 8,
//         L: 22,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW10',
//         type: '22MOV10',
//         partNumber: '1221045P2',
//         description: 'XLIF 3D 10x22x45mm - 10°',
//         material: 'MODULUS',
//         H: 10,
//         L: 22,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW10',
//         type: '22MOV10',
//         partNumber: '1221050P2',
//         description: 'XLIF 3D 10x22x50mm - 10°',
//         material: 'MODULUS',
//         H: 10,
//         L: 22,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW10',
//         type: '22MOV10',
//         partNumber: '1221055P2',
//         description: 'XLIF 3D 10x22x55mm - 10°',
//         material: 'MODULUS',
//         H: 10,
//         L: 22,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW10',
//         type: '22MOV10',
//         partNumber: '1221060P2',
//         description: 'XLIF 3D 10x22x60mm - 10°',
//         material: 'MODULUS',
//         H: 10,
//         L: 22,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW10',
//         type: '22MOV10',
//         partNumber: '1221245P2',
//         description: 'XLIF 3D 12x22x45mm - 10°',
//         material: 'MODULUS',
//         H: 12,
//         L: 22,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW10',
//         type: '22MOV10',
//         partNumber: '1221250P2',
//         description: 'XLIF 3D 12x22x50mm - 10°',
//         material: 'MODULUS',
//         H: 12,
//         L: 22,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW10',
//         type: '22MOV10',
//         partNumber: '1221255P2',
//         description: 'XLIF 3D 12x22x55mm - 10°',
//         material: 'MODULUS',
//         H: 12,
//         L: 22,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW10',
//         type: '22MOV10',
//         partNumber: '1221260P2',
//         description: 'XLIF 3D 12x22x60mm - 10°',
//         material: 'MODULUS',
//         H: 12,
//         L: 22,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW15',
//         type: '22MOV15',
//         partNumber: '1225845P2',
//         description: 'XLIF 3D 8x22x45mm - 15°',
//         material: 'MODULUS',
//         H: 8,
//         L: 22,
//         W: 45,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW15',
//         type: '22MOV15',
//         partNumber: '1225850P2',
//         description: 'XLIF 3D 8x22x50mm - 15°',
//         material: 'MODULUS',
//         H: 8,
//         L: 22,
//         W: 50,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW15',
//         type: '22MOV15',
//         partNumber: '1225855P2',
//         description: 'XLIF 3D 8x22x55mm - 15°',
//         material: 'MODULUS',
//         H: 8,
//         L: 22,
//         W: 55,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW15',
//         type: '22MOV15',
//         partNumber: '1225860P2',
//         description: 'XLIF 3D 8x22x60mm - 15°',
//         material: 'MODULUS',
//         H: 8,
//         L: 22,
//         W: 60,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW15',
//         type: '22MOV15',
//         partNumber: '1225045P2',
//         description: 'XLIF 3D 10x22x45mm - 15°',
//         material: 'MODULUS',
//         H: 10,
//         L: 22,
//         W: 45,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW15',
//         type: '22MOV15',
//         partNumber: '1225050P2',
//         description: 'XLIF 3D 10x22x50mm - 15°',
//         material: 'MODULUS',
//         H: 10,
//         L: 22,
//         W: 50,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW15',
//         type: '22MOV15',
//         partNumber: '1225055P2',
//         description: 'XLIF 3D 10x22x55mm - 15°',
//         material: 'MODULUS',
//         H: 10,
//         L: 22,
//         W: 55,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW15',
//         type: '22MOV15',
//         partNumber: '1225060P2',
//         description: 'XLIF 3D 10x22x60mm - 15°',
//         material: 'MODULUS',
//         H: 10,
//         L: 22,
//         W: 60,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW15',
//         type: '22MOV15',
//         partNumber: '1225245P2',
//         description: 'XLIF 3D 12x22x45mm - 15°',
//         material: 'MODULUS',
//         H: 12,
//         L: 22,
//         W: 45,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW15',
//         type: '22MOV15',
//         partNumber: '1225250P2',
//         description: 'XLIF 3D 12x22x50mm - 15°',
//         material: 'MODULUS',
//         H: 12,
//         L: 22,
//         W: 50,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW15',
//         type: '22MOV15',
//         partNumber: '1225255P2',
//         description: 'XLIF 3D 12x22x55mm - 15°',
//         material: 'MODULUS',
//         H: 12,
//         L: 22,
//         W: 55,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLW15',
//         type: '22MOV15',
//         partNumber: '1225260P2',
//         description: 'XLIF 3D 12x22x60mm - 15°',
//         material: 'MODULUS',
//         H: 12,
//         L: 22,
//         W: 60,
//         lordosis: 15,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW0',
//         type: '26MOV0',
//         partNumber: '1260845P2',
//         description: 'XLIF 3D 8x26x45mm - 0°',
//         material: 'MODULUS',
//         H: 8,
//         L: 26,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW0',
//         type: '26MOV0',
//         partNumber: '1260850P2',
//         description: 'XLIF 3D 8x26x50mm - 0°',
//         material: 'MODULUS',
//         H: 8,
//         L: 26,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW0',
//         type: '26MOV0',
//         partNumber: '1260855P2',
//         description: 'XLIF 3D 8x26x55mm - 0°',
//         material: 'MODULUS',
//         H: 8,
//         L: 26,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW0',
//         type: '26MOV0',
//         partNumber: '1260860P2',
//         description: 'XLIF 3D 8x26x60mm - 0°',
//         material: 'MODULUS',
//         H: 8,
//         L: 26,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW0',
//         type: '26MOV0',
//         partNumber: '1260045P2',
//         description: 'XLIF 3D 10x26x45mm - 0°',
//         material: 'MODULUS',
//         H: 10,
//         L: 26,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW0',
//         type: '26MOV0',
//         partNumber: '1260050P2',
//         description: 'XLIF 3D 10x26x50mm - 0°',
//         material: 'MODULUS',
//         H: 10,
//         L: 26,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW0',
//         type: '26MOV0',
//         partNumber: '1260055P2',
//         description: 'XLIF 3D 10x26x55mm - 0°',
//         material: 'MODULUS',
//         H: 10,
//         L: 26,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW0',
//         type: '26MOV0',
//         partNumber: '1260060P2',
//         description: 'XLIF 3D 10x26x60mm - 0°',
//         material: 'MODULUS',
//         H: 10,
//         L: 26,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW0',
//         type: '26MOV0',
//         partNumber: '1260245P2',
//         description: 'XLIF 3D 12x26x45mm - 0°',
//         material: 'MODULUS',
//         H: 12,
//         L: 26,
//         W: 45,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW0',
//         type: '26MOV0',
//         partNumber: '1260250P2',
//         description: 'XLIF 3D 12x26x50mm - 0°',
//         material: 'MODULUS',
//         H: 12,
//         L: 26,
//         W: 50,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW0',
//         type: '26MOV0',
//         partNumber: '1260255P2',
//         description: 'XLIF 3D 12x26x55mm - 0°',
//         material: 'MODULUS',
//         H: 12,
//         L: 26,
//         W: 55,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW0',
//         type: '26MOV0',
//         partNumber: '1260260P2',
//         description: 'XLIF 3D 12x26x60mm - 0°',
//         material: 'MODULUS',
//         H: 12,
//         L: 26,
//         W: 60,
//         lordosis: 0,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW10',
//         type: '26MOV10',
//         partNumber: '1261845P2',
//         description: 'XLIF 3D 8x26x45mm - 10°',
//         material: 'MODULUS',
//         H: 8,
//         L: 26,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW10',
//         type: '26MOV10',
//         partNumber: '1261850P2',
//         description: 'XLIF 3D 8x26x50mm - 10°',
//         material: 'MODULUS',
//         H: 8,
//         L: 26,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW10',
//         type: '26MOV10',
//         partNumber: '1261855P2',
//         description: 'XLIF 3D 8x26x55mm - 10°',
//         material: 'MODULUS',
//         H: 8,
//         L: 26,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW10',
//         type: '26MOV10',
//         partNumber: '1261860P2',
//         description: 'XLIF 3D 8x26x60mm - 10°',
//         material: 'MODULUS',
//         H: 8,
//         L: 26,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW10',
//         type: '26MOV10',
//         partNumber: '1261045P2',
//         description: 'XLIF 3D 10x26x45mm - 10°',
//         material: 'MODULUS',
//         H: 10,
//         L: 26,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW10',
//         type: '26MOV10',
//         partNumber: '1261050P2',
//         description: 'XLIF 3D 10x26x50mm - 10°',
//         material: 'MODULUS',
//         H: 10,
//         L: 26,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW10',
//         type: '26MOV10',
//         partNumber: '1261055P2',
//         description: 'XLIF 3D 10x26x55mm - 10°',
//         material: 'MODULUS',
//         H: 10,
//         L: 26,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW10',
//         type: '26MOV10',
//         partNumber: '1261060P2',
//         description: 'XLIF 3D 10x26x60mm - 10°',
//         material: 'MODULUS',
//         H: 10,
//         L: 26,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW10',
//         type: '26MOV10',
//         partNumber: '1261245P2',
//         description: 'XLIF 3D 12x26x45mm - 10°',
//         material: 'MODULUS',
//         H: 12,
//         L: 26,
//         W: 45,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW10',
//         type: '26MOV10',
//         partNumber: '1261250P2',
//         description: 'XLIF 3D 12x26x50mm - 10°',
//         material: 'MODULUS',
//         H: 12,
//         L: 26,
//         W: 50,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW10',
//         type: '26MOV10',
//         partNumber: '1261255P2',
//         description: 'XLIF 3D 12x26x55mm - 10°',
//         material: 'MODULUS',
//         H: 12,
//         L: 26,
//         W: 55,
//         lordosis: 10,
//         qtyInSet: 2
//     },
//     {
//         setType: 'MDLUSXLXW10',
//         type: '26MOV10',
//         partNumber: '1261260P2',
//         description: 'XLIF 3D 12x26x60mm - 10°',
//         material: 'MODULUS',
//         H: 12,
//         L: 26,
//         W: 60,
//         lordosis: 10,
//         qtyInSet: 2
//     }
// ]
